name: Build and Release Debian Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_packages:
    strategy:
      matrix:
        architecture: [armhf, arm64]
        include: 
          - architecture: armhf
            image: arm32v7/ubuntu:20.04
            platform: linux/arm/v7
          - architecture: arm64
            image: arm64v8/ubuntu:20.04
            platform: linux/arm64/v8
    name: Build Debian Package for ${{ matrix.architecture }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.architecture }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/workflows/Dockerfile
          platforms: ${{ matrix.platform }}
          load: true
          tags: builder-${{ matrix.architecture }}:latest
          build-args: |
            IMAGE=${{ matrix.image }}

      - name: Build Debian package in Docker
        run: |
          docker run --rm --platform ${{ matrix.platform }} -v $PWD:/workspace builder-${{ matrix.architecture }} /bin/bash -c "cd /workspace && debuild -us -uc -b && cp -a ../*.deb ./"
        shell: bash

      - name: Get version
        id: get_version
        run: |
          echo "version=$(dpkg-parsechangelog --show-field Version)" >> $GITHUB_OUTPUT

      - name: Get commit hash
        id: get_commit_hash
        uses: prompt/actions-commit-hash@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.short }}-${{ matrix.architecture }}
          tag_name: v${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.short }}-${{ matrix.architecture }}
          generate_release_notes: true
          files: |
            ./*.deb